#!/bin/bash

if [ ! -n "$1" ] ;then
    echo "Usage:"
    echo "    save_config factory: save configuration as factory backup"
    echo "    save_config recent: save configuration as factory backup"
    exit
fi


case $1 in
"factory")
                lvremove -f VolGroup/lv_root.factory 1>/dev/null
                lvcreate -s -L 10G -n lv_root.factory VolGroup/lv_root 1>/dev/null
		exit
                ;;
"recent")
                lvremove -f VolGroup/lv_root.recent 1>/dev/null
                lvcreate -s -L 10G -n lv_root.recent VolGroup/lv_root 1>/dev/null
		exit
                ;;
*) 
    echo "Usage:"
    echo "    save_config factory: save configuration as factory backup"
    echo "    save_config recent: save configuration as factory backup"
    exit;;
esac
