#!/bin/bash

RULE_FILE="/etc/udev/rules.d/70-persistent-net.rules"
cat>$RULE_FILE<<EOF

# This file was automatically generated by the /lib/udev/write_net_rules
# program, run by the persistent-net-generator.rules rules file.
#
# You can modify it, as long as you keep each rule on a single
# line, and change only the value of the NAME= key.

# PCI device 0x8086:0x1521 (igb)
SUBSYSTEM=="net", ACTION=="add", BUS=="pci", KERNELS=="0000:03:00.0", NAME="eth0"

# PCI device 0x8086:0x1521 (igb)
SUBSYSTEM=="net", ACTION=="add", BUS=="pci", KERNELS=="0000:04:00.0", NAME="eth1"

# PCI device 0x8086:0x1521 (igb)
SUBSYSTEM=="net", ACTION=="add", BUS=="pci", KERNELS=="0000:05:00.0", NAME="eth2"

# PCI device 0x8086:0x1521 (igb)
SUBSYSTEM=="net", ACTION=="add", BUS=="pci", KERNELS=="0000:06:00.0", NAME="eth3"

# PCI device 0x8086:0x1521 (igb)
SUBSYSTEM=="net", ACTION=="add", BUS=="pci", KERNELS=="0000:07:00.0", NAME="eth4"

# PCI device 0x8086:0x1521 (igb)
SUBSYSTEM=="net", ACTION=="add", BUS=="pci", KERNELS=="0000:08:00.0", NAME="eth5"

# PCI device 0x8086:0x1521 (igb)
SUBSYSTEM=="net", ACTION=="add", BUS=="pci", KERNELS=="0000:09:00.0", NAME="eth6"

# PCI device 0x8086:0x1521 (igb)
SUBSYSTEM=="net", ACTION=="add", BUS=="pci", KERNELS=="0000:00:19.0", NAME="eth7"
EOF


